- Dockerfile
- hatchery/config.go
- Add vim to the image and add a debug log for "more-configs"
> Add vim and debug log

- hatchery/pods.go
- openapis/openapi.yaml
Add `PodConditions` and `ContainerStates` info to responses returned from `/status` endpoint (for https://github.com/uc-cdis/data-portal/pull/847)
- Add `PodConditions` and `ContainerStates` info to responses returned from `/status` endpoint
> PXP-7919 Feat/more status

- go.mod
- go.sum
- hatchery/hatchery.go
- hatchery/pods.go
- main.go
- Add DD APM AWS and K8s trace with context
- Add DD APM continuous profiler
> add more tracer

- openapis/openapi.yaml
- Updated OpenAPI doc to include the `Not Found` enum status.
> docs(openapi): update openapi for enum status Not Found

- hatchery/config.go
- hatchery/pods.go
Jira Ticket: [HP-651](https://ctds-planx.atlassian.net/browse/HP-651)
Add ability to add a default pay model if a pay model for user hasn't been specified. 
This should help us with the work of adding and removing users from blanket billing. 
Also tackled [HP-617](https://ctds-planx.atlassian.net/browse/HP-617)
Tested manually in qa-heal.
> [HP-651] Add default paymodel

- .github/workflows/golang-ci-workflow.yaml
Jira Ticket: N/A, but see https://github.com/uc-cdis/.github/pull/16
- using the new github action instead of the reusable workflow
> using new github action for coverage report

- .github/workflows/golang-ci-workflow.yaml
- hatchery/config_test.go
- hatchery/dockstore_test.go
- hatchery/pods_test.go
Jira Ticket: [PXP-10137](https://ctds-planx.atlassian.net/browse/PXP-10137)
* Fix linter errors
> (PXP-10137) fix/linter errors

- hatchery/efs.go
- hatchery/transitgateway.go
Fixes a bug where if the commons + username equates to longer than 64 characters, the ECS launch wouldn't work.
> Strip certain tokens at max length

- hatchery/pods.go
Jira Ticket: [GPE-735](https://ctds-planx.atlassian.net/browse/GPE-735)
Set enableServiceLinks to false in workspace pods.
> Disable service links in workspaces

- .gitignore
- hatchery/hatchery.go
- main.go
Jira Ticket: [PPS-193](https://ctds-planx.atlassian.net/browse/PPS-193) [PPS-194](https://ctds-planx.atlassian.net/browse/PPS-194)
- vulnerability fixes
[PPS-193]: https://ctds-planx.atlassian.net/browse/PPS-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PPS-194]: https://ctds-planx.atlassian.net/browse/PPS-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PPS-193/PPS-194 fix

- .github/labeler.yml
- .github/workflows/labeler.yml
Jira Ticket: [GQE-74](https://ctds-planx.atlassian.net/browse/GQE-74)
[GQE-74]: https://ctds-planx.atlassian.net/browse/GQE-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> adding labeler to hatchery

- hatchery/ec2.go
- hatchery/transitgateway.go
- hatchery/vpc.go
Jira Ticket: [BRH-552](https://ctds-planx.atlassian.net/browse/BRH-552)
- Add support for VPC's with multiple CIDR's
[BRH-552]: https://ctds-planx.atlassian.net/browse/BRH-552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add support for VPC with multiple CIDR blocks

- doc/howto/configuration.md
- hatchery/config.go
- hatchery/config_test.go
- hatchery/hatchery.go
- hatchery/helpers.go
- hatchery/iam.go
- hatchery/nextflow.go
- hatchery/pods.go
- hatchery/pods_test.go
- hatchery/vpc.go
- main.go
Nextflow direct pay + squid updates:
- remove duplication between blanket billing implementation and direct pay implementation
- update logs
- remove `CreateNextflowGlobalResources()` logic
- retroactively add new changes from `feat/nextflow` branch
> Nextflow direct pay + squid - remove duplication

- doc/howto/configuration.md
- hatchery/config.go
- hatchery/config_test.go
- hatchery/hatchery.go
- hatchery/helpers.go
- hatchery/iam.go
- hatchery/nextflow.go
- hatchery/pods.go
- hatchery/pods_test.go
- hatchery/vpc.go
- main.go
- testData/testConfig.json
- Setup and tearown Direct Pay level nextflow resources including squid
> direct pay + squid nextflow

- hatchery/nextflow.go
- Fix Nextflow Batch compute environment to be user-specific
> Fix Nextflow Batch compute env to be user-specific

- hatchery/vpc.go
- Replace route to IGW if it already exists
> Replace route to IGW if it already exists

- hatchery/nextflow.go
- Nextflow in Batch: Ignore "invalid" state before updating a compute environment, instead of waiting for it to be valid
> Allow invalid state when updating compute env

- hatchery/nextflow.go
- Add ability to authenticate AWS batch with ECR repositories via user data
> Add ability to authenticate AWS batch with private ECR repositories

- hatchery/nextflow.go
Jira Ticket: [MIDRC-594](https://ctds-planx.atlassian.net/browse/MIDRC-594)
- Nextflow: Configure the AMI for both CPU and GPU instances
[MIDRC-594]: https://ctds-planx.atlassian.net/browse/MIDRC-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MIDRC-594 Configure the AMI for all image types

- doc/howto/configuration.md
- hatchery/hatchery.go
- hatchery/nextflow.go
- hatchery/nextflow_test.go
Jira Ticket: [MIDRC-464](https://ctds-planx.atlassian.net/browse/MIDRC-464)
- Nextflow: Support for username placeholder in `job-image-whitelist` configuration
[MIDRC-464]: https://ctds-planx.atlassian.net/browse/MIDRC-464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MIDRC-464 Support for username placeholder in Nextflow whitelist

- hatchery/prisma.go
- Fix the prisma defender version. Long term we should read this from config, this is a hotfix.
> Fix prisma cloud integration

- .github/labeler.yml
- .github/workflows/labeler.yml
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
> add labeler workflow to hatchery

- hatchery/gen3licenseusermaps.go
- hatchery/hatchery.go
- hatchery/helpers.go
- hatchery/nextflow.go
- hatchery/nextflow_test.go
- hatchery/tests_setup.go
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/MIDRC-650
- Cancel Nextflow jobs on workspace termination
> MIDRC-650 Cancel Nextflow jobs on workspace termination

- doc/howto/configuration.md
- hatchery/config.go
- hatchery/hatchery.go
- hatchery/hatchery_test.go
- hatchery/nextflow.go
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/MIDRC-679
- The Nextflow sample configuration now includes a public image that is configurable instead of hardcoded
> MIDRC-679 Nextflow - Configurable sample config public image

- hatchery/nextflow.go
Link to JIRA ticket if there is one: 
- Fix the logic when handling errors around creating instance profiles for nextflow/ batch
> MIDRC-692 - Fix logic in error handling of instance profile

- hatchery/iam.go
- hatchery/nextflow.go
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/MIDRC-711
- Nextflow: enable KMS encryption on Nextflow-managed S3 buckets
> MIDRC-711 KMS encryption on Nextflow buckets

- hatchery/nextflow.go
- hatchery/nextflow_test.go
Add ticket numbers for nextflow todos
> Add ticket numbers for nextflow todos

- doc/explanation/authorization.md
- Add more details to container authorization docs
> Update authorization docs

- Dockerfile
- hatchery/nextflow.go
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/MIDRC-811
- Add batch:TagResource to user policy for nextflow / batch
> MIDRC-811 Add batch:TagResource to user policy

- doc/howto/jupyterNotebook.md
- doc/howto/noVNCFirefox.md
- testData/testConfig.json
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/HP-1994
- Don't advocate mounting `/data` into `/pd`
> fix: don't promote mounting /data into /pd

- hatchery/pods.go
Link to JIRA ticket if there is one: 
- when launching workspaces in a separate cluster use a workspace node to proxy to.
> Use role=jupyter for labelsector in nodeip
